export const testData = [{
    taskId:5,
    mySummary:"XXX",
    myDescription:"my Description 5",
    myPriority:"high",
    myDate:"2019-02-24",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS"
},
{
    taskId:3,
    mySummary:"YYY",
    myDescription:"my Description 3",
    myPriority:"medium",
    myDate:"2018-09-13",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:1,
    mySummary:"ZZZZ",
    myDescription:"my Description 1",
    myPriority:"medium",
    myDate:"2004-02-22",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"COMPLETED",
},
{
    taskId:6,
    mySummary:"ABCD",
    myDescription:"my Description 6",
    myPriority:"low",
    myDate:"2008-12-31",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:4,
    mySummary:"ABXX",
    myDescription:"my Description 4",
    myPriority:"medium",
    myDate:"1958-02-12",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"COMPLETED",
},
{
    taskId:2,
    mySummary:"AZXX",
    myDescription:"my Description 2",
    myPriority:"low",
    myDate:"2014-10-22",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:10,
    mySummary:"AAZSXX",
    myDescription:"my Description 10",
    myPriority:"low",
    myDate:"2014-10-18",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"COMPLETED",
},
{
    taskId:8,
    mySummary:"APOIXX",
    myDescription:"my Description 8",
    myPriority:"low",
    myDate:"2004-04-08",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:12,
    mySummary:"YELLOW",
    myDescription:"my Description 12",
    myPriority:"medium",
    myDate:"2010-01-14",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:14,
    mySummary:"REDXXF",
    myDescription:"my Description 14",
    myPriority:"high",
    myDate:"2007-11-15",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:13,
    mySummary:"QWAZXX",
    myDescription:"my Description 13",
    myPriority:"medium",
    myDate:"2002-06-02",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:11,
    mySummary:"DSFFD",
    myDescription:"my Description 11",
    myPriority:"medium",
    myDate:"2000-05-12",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:9,
    mySummary:"AZXX",
    myDescription:"my Description 9",
    myPriority:"high",
    myDate:"1997-05-21",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
{
    taskId:7,
    mySummary:"ZZAZXX",
    myDescription:"my Description 7",
    myPriority:"low",
    myDate:"1997-05-21",
    timeStamp: `${new Date().getFullYear()}-${new Date().getMonth()+1}-${new Date().getDate()}T${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}:${new Date().getMilliseconds()}`,
    status:"IN_PROGRESS",
},
]