const FETCH_TODOS = 'FETCH_TODOS';
const UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB';
const DELETE_TODO = 'DELETE_TODO';
const ADD_TODO = 'ADD_TODO';
const UPDATE_TODO = 'UPDATE_TODO';
const BULK_DONE = 'BULK_DONE';
const BULK_PENDING = 'BULK_PENDING';
const GLOBAL_SEARCH = 'GLOBAL_SEARCH';
export {
    FETCH_TODOS,
    UPDATE_ACTIVE_TAB,
    DELETE_TODO,
    ADD_TODO,
    UPDATE_TODO,
    BULK_DONE,
    BULK_PENDING,
    GLOBAL_SEARCH
}
