/**
 * Created by Rakesh Peela
 * Date: 16-Apr-2020
 * Time: 11:47 PM
 */

const APP_SHOW_MODAL = "APP_SHOW_MODAL";
const APP_HIDE_MODAL = "APP_HIDE_MODAL";
const SET_SORT_ORDER = "SET_SORT_ORDER";
const SET_GROUPBY_KEY = "SET_GROUPBY_KEY";

const API_STARTED = "API_STARTED";
const API_COMPLETED = "API_COMPLETED";

const MODAL_TYPES = {
    ADD_TASK_MODAL: "ADD_TASK_MODAL",
    DELETE_TASK_MODAL: "DELETE_TASK_MODAL",
    EDIT_TASK_MODAL: "EDIT_TASK_MODAL",
    VIEW_TASK_MODAL: "VIEW_TASK_MODAL",
}

export {
    APP_SHOW_MODAL,
    APP_HIDE_MODAL,
    SET_SORT_ORDER,
    SET_GROUPBY_KEY,
    API_COMPLETED,
    API_STARTED,
    MODAL_TYPES,
}