export const taskConstants = {
  CREATE_TASK: "CREATE_TASK",
  SUCCESS_CREATE_TASK: "SUCCESS_CREATE_TASK",
  ERROR_CREATE_TASK: "ERROR_CREATE_TASK",
  UPDATE_TASK: "UPDATE_TAKS",
  DELETE_TASK: "DELETE_TASK",
  LOAD_TASK: "LOAD_TASK",
  SUCCESS_LOAD_TASK: "SUCCESS_LOAD_TASK",
  ERROR_LOAD_TASK: "ERROR_LOAD_TASK",
};
