const APP_SHOW_MODAL = "APP_SHOW_MODAL";
const APP_HIDE_MODAL = "APP_HIDE_MODAL";
const SET_SORT_ORDER = "SET_SORT_ORDER";
const SET_GROUPBY_KEY = "SET_GROUPBY_KEY";

export { APP_SHOW_MODAL, APP_HIDE_MODAL, SET_SORT_ORDER, SET_GROUPBY_KEY };
