const TOGGLE_TASK_STATE = "TOGGLE_TASK_STATE";
const DELETE_TASK = "DELETE_TASK";
const EDIT_TASK = "EDIT_TASK";
const ADD_TASK = "ADD_TASK";

export {
    DELETE_TASK,
    EDIT_TASK,
    ADD_TASK,
    TOGGLE_TASK_STATE,
}