export const columnOptions = [
  {
    name: "title",
    label: "Title",
    allowSort: true,
    allowSearch: true,
    groupBy: false,
    showHeader: true,
    isAction: false,
    min: 10,
    max: 140
  },
  {
    name: "description",
    label: "Description",
    allowSort: false,
    allowSearch: true,
    groupBy: false,
    showHeader: false,
    isAction: false,
    min: 10,
    max: 500
  },
  {
    name: "currentState",
    label: "State",
    allowSort: true,
    allowSearch: true,
    groupBy: false,
    showHeader: true,
    isAction: false,
  },
  {
    name: "createdAt",
    label: "Created At",
    allowSort: true,
    allowSearch: false,
    groupBy: true,
    showHeader: true,
    isAction: false,
  },
  {
    name: "dueDate",
    label: "Due Date",
    allowSort: true,
    allowSearch: false,
    groupBy: true,
    showHeader: true,
    isAction: false,
  },
  {
    name: "priority",
    label: "Priority",
    allowSort: true,
    allowSearch: false,
    showHeader: true,
    groupBy: true,
    options: ['high', 'medium', 'low']
  },
  {
    name: "actions",
    label: "Actions",
    allowSort: false,
    allowSearch: false,
    groupBy: false,
    showHeader: true,
    isAction: true,
  },
];
