export const fieldSet = [
  {
    name: "title",
    label: "Summary",
    allowSort: true,
    allowSearch: true,
    groupBy: false,
    isAction: false,
  },
  {
    name: "description",
    label: "Description",
    allowSort: false,
    allowSearch: true,
    groupBy: false,
    isAction: false,
  },
  {
    name: "createdAt",
    label: "Created At",
    allowSort: false,
    allowSearch: false,
    groupBy: true,
    isAction: false,
  },
  {
    name: "dueDate",
    label: "Due Date",
    allowSort: false,
    allowSearch: false,
    groupBy: false,
    isAction: false,
  },
  {
    name: "priority",
    label: "Priority",
    allowSort: true,
    allowSearch: false,
    groupBy: false,
  },
  {
    name: "actions",
    label: "Actions",
    allowSort: false,
    allowSearch: false,
    groupBy: false,
    isAction: true,
  },
];
